export const GET_USERS_LIST = 'GET_USERS_LIST';
export const GET_USERS_LIST_SUCCESS = 'GET_USERS_LIST_SUCCESS';
export const GET_USERS_LIST_FAILED = 'GET_USERS_LIST_FAILED';
export const DELETE_USER = 'DELETE_USER';
